import { useState, type FormEvent } from 'react';
import { t, useLocale } from '../../app/i18n';
import type { Client, Currency } from '../../domain/types';
type ConversionSubmission = Readonly<{ amount: number; currency: Currency; clientId?: string; primaryMemberId?: string }>;
export function LeadConversionForm({ clients, linkedClientId, onConfirm, onCancel }: { clients: readonly Client[]; linkedClientId?: string; onConfirm: (payment: ConversionSubmission) => void; onCancel: () => void }) {
  const locale = useLocale(); const [amount, setAmount] = useState(''); const [currency, setCurrency] = useState<Currency | ''>(''); const [clientId, setClientId] = useState(linkedClientId ?? ''); const initialClient = clients.find((client) => client.id === linkedClientId); const [primaryMemberId, setPrimaryMemberId] = useState(initialClient?.members?.find((member) => member.status === 'active')?.id ?? ''); const [error, setError] = useState(''); const label = (key: import('../../app/i18n').TranslationKey) => t(key, locale);
  const selectedClient = clients.find((client) => client.id === clientId); const activeMembers = selectedClient?.members?.filter((member) => member.status === 'active') ?? [];
  function selectClient(nextClientId: string) { setClientId(nextClientId); setPrimaryMemberId(clients.find((client) => client.id === nextClientId)?.members?.find((member) => member.status === 'active')?.id ?? ''); }
  function submit(event: FormEvent) { event.preventDefault(); const numericAmount = Number(amount); if (!Number.isFinite(numericAmount) || numericAmount < 0 || currency === '') { setError(label('conversionRequired')); return; } if (clientId && !primaryMemberId) { setError(label('primaryContactRequiredForConversion')); return; } onConfirm({ amount: numericAmount, currency, ...(clientId ? { clientId, primaryMemberId } : {}) }); }
  return <form className="conversion-form" onSubmit={submit}><h3>{label('recordFirstPayment')}</h3><p>{label('conversionDescription')}</p>{clients.length > 0 && <label>{label('client')}<select aria-label={label('client')} value={clientId} onChange={(event) => selectClient(event.target.value)}><option value="">{label('createNewClient')}</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label>}{clientId && <label>{label('primaryContact')}<select aria-label={label('primaryContact')} disabled={activeMembers.length === 0} onChange={(event) => setPrimaryMemberId(event.target.value)} value={primaryMemberId}><option value="">{activeMembers.length === 0 ? label('primaryContactRequiredForConversion') : label('select')}</option>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label>}<label>{label('advance')}<input aria-label={label('advance')} inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>{label('currency')}<select aria-label={label('currency')} value={currency} onChange={(event) => setCurrency(event.target.value as Currency | '')}><option value="">{label('select')}</option><option value="USD">USD</option><option value="MXN">MXN</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={onCancel}>{label('cancel')}</button><button className="primary-button" type="submit">{label('confirmSale')}</button></div></form>;
}
